In [1]:
import os
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import cv2

# Load the trained model
model = load_model('models\Final_CNN_with25epochs.h5')

# Folder containing the input images
input_folder = 'Output_frames'

# List to store outputs
outputs = []

In [2]:
import tensorflow as tf

In [5]:
# Loop through each image in the folder
for filename in os.listdir(input_folder):
    # Skip non-image files
    print("Filename : ")
    print(filename)
    if not filename.endswith('.jpg'):
        continue


    img=cv2.imread(input_folder+"/"+filename)
    print(img.shape)

    #Detecting only the face part
    clf = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    #faces contains coordinates of the face
    faces = clf.detectMultiScale(img,scaleFactor =1.1,minNeighbors=5,minSize=(96,96),flags=cv2.CASCADE_SCALE_IMAGE)
    print(f'Faces : {faces}\n')

    # for(x,y,width,height) in faces:
    #     temp=cv2.rectangle(img,(x,y),(x+width,y+height),(255,255,0),2)

    input_image = cv2.cvtColor(img[faces[0][1]:(faces[0][1]+faces[0][3]),faces[0][0]:(faces[0][0]+faces[0][3])],cv2.COLOR_BGR2RGB)

    resize = tf.image.resize(input_image, (96,96))
    resize=resize/255
    img = np.expand_dims(resize, axis=0)


    # Predict using the model
    # print(img)
    output = model.predict(img)
    print(output)

    # Append the output to the list
    outputs.append(output)




Filename : 
IMG-20240319-WA0002.jpg
(900, 1600, 3)
Faces : [[656 379 316 316]]

1/1 [==============================] - 0s 26ms/step
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
Filename : 
IMG-20240319-WA0003.jpg
(900, 1600, 3)
Faces : [[659 375 325 325]]

1/1 [==============================] - 0s 23ms/step
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
Filename : 
IMG-20240319-WA0004.jpg
(900, 1600, 3)
Faces : [[661 372 331 331]]

1/1 [==============================] - 0s 26ms/step
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
Filename : 
IMG-20240319-WA0005.jpg
(900, 1600, 3)
Faces : [[664 377 323 323]]

1/1 [==============================] - 0s 23ms/step
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
Filename : 
IMG-20240319-WA0006.jpg
(900, 1600, 3)
Faces : [[667 377 323 323]]

1/1 [===========

In [47]:
# Convert the list of outputs to a numpy array
result = np.array(outputs)

# Sum up all the values
final_score = np.sum(result)

print(f"Final score: {final_score}")

Final score: 4.999999523162842


In [48]:
len(result)

5

In [49]:
sum=0
for elements in result:
    print(elements)
    for i in range(0,4):
        sum+=elements[0][i]
    #sum+=elements[0][7]
print(sum/len(result))


if sum <= 0.5:
    print("The person is not stressed")
else:
    print("The preson is stressed")

[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
[[0.12941767 0.11383781 0.12409376 0.1080412  0.15505257 0.10103357
  0.1059204  0.16260298]]
0.4753904417157173
The preson is stressed


In [50]:
result

array([[[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]],

       [[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]],

       [[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]],

       [[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]],

       [[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]]], dtype=float32)

In [51]:
elements

array([[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
        0.10103357, 0.1059204 , 0.16260298]], dtype=float32)

In [52]:
outputs

[array([[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]], dtype=float32),
 array([[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]], dtype=float32),
 array([[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]], dtype=float32),
 array([[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]], dtype=float32),
 array([[0.12941767, 0.11383781, 0.12409376, 0.1080412 , 0.15505257,
         0.10103357, 0.1059204 , 0.16260298]], dtype=float32)]